---
# tasks file for apache2
- name: install web component
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: ensure apache2 started
  service: name=apache2 state=started

- name: ensure liabappapache installed
  apache2_module: state=present name=wsgi
  notify: restart apache2


- name: deactivate default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2

