# stop all the services
---
  #start load balancer
  - hosts: loadbalancer
    gather_facts: false
    become: true
    tasks:
      - name: ensure nginx started
        service: name=nginx state=restarted

  #start webserver
  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: ensure apache2 started
        service: name=apache2 state=restarted

  #start database
  - hosts: database
    become: true
    tasks:
      - name: ensure mysql started
        service: name=mysql state=restarted
