# stop all the services
---
  #stop load balancer
  - hosts: loadbalancer
    become: true
    tasks:
      - name: ensure nginx stopped
        service: name=nginx state=stopped

  #stop webserver
  - hosts: webserver
    become: true
    tasks:
      - name: ensure apache2 stopped
        service: name=apache2 state=stopped

  #stop database
  - hosts: database
    become: true
    tasks:
      - name: ensure mysql stopped
        service: name=mysql state=stopped
